### ISSUE TITLE
Can't open map

### ISSUE THREAD

**Issue by schollz** [sjsafranek/gospatial#1]
```
[FIND] INFO  | 2016/03/17 17:57:16.873251 generalHandlers.go:20: 127.0.0.1:42630 GET /map/fb922119c7514c4cad7108f2c6953de0 [200]
2016/03/17 13:57:16 http: panic serving 127.0.0.1:42630: runtime error: invalid memory address or nil pointer dereference
goroutine 18 [running]:
net/http.(*conn).serve.func1(0xc820147300)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x848a80, 0xc82000a230)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:79 +0x3c
html/template.(*Template).Execute(0x0, 0x7f8e35332458, 0xc82013e270, 0x83b960, 0xc820172b10, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:101 +0x34
gospatial/app.MapHandler(0x7f8e35332388, 0xc82013e270, 0xc820156620)
	/home/zack/Documents/gospatial2/src/gospatial/app/generalHandlers.go:21 +0x461
net/http.HandlerFunc.ServeHTTP(0x9a5e58, 0x7f8e35332388, 0xc82013e270, 0xc820156620)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820136000, 0x7f8e35332388, 0xc82013e270, 0xc820156620)
	/home/zack/Documents/gospatial2/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.serverHandler.ServeHTTP(0xc820147280, 0x7f8e35332388, 0xc82013e270, 0xc820156620)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820147300)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
[FIND] WARN  | 2016/03/17 17:57:21.335768 generalHandlers.go:23: 127.0.0.1:42633 GET /map/fb922119c7514c4cad7108f2c6953de0 [401]
[FIND] INFO  | 2016/03/17 17:57:23.586378 generalHandlers.go:20: 127.0.0.1:42633 GET /map/fb922119c7514c4cad7108f2c6953de0 [200]
2016/03/17 13:57:23 http: panic serving 127.0.0.1:42633: runtime error: invalid memory address or nil pointer dereference
goroutine 19 [running]:
net/http.(*conn).serve.func1(0xc820147500)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x848a80, 0xc82000a230)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:79 +0x3c
html/template.(*Template).Execute(0x0, 0x7f8e35332458, 0xc82013e5b0, 0x83b960, 0xc820172d40, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:101 +0x34
gospatial/app.MapHandler(0x7f8e35332388, 0xc82013e5b0, 0xc8201567e0)
	/home/zack/Documents/gospatial2/src/gospatial/app/generalHandlers.go:21 +0x461
net/http.HandlerFunc.ServeHTTP(0x9a5e58, 0x7f8e35332388, 0xc82013e5b0, 0xc8201567e0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820136000, 0x7f8e35332388, 0xc82013e5b0, 0xc8201567e0)
	/home/zack/Documents/gospatial2/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.serverHandler.ServeHTTP(0xc820147280, 0x7f8e35332388, 0xc82013e5b0, 0xc8201567e0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820147500)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
[FIND] INFO  | 2016/03/17 17:57:23.597103 generalHandlers.go:20: 127.0.0.1:42634 GET /map/fb922119c7514c4cad7108f2c6953de0 [200]
2016/03/17 13:57:23 http: panic serving 127.0.0.1:42634: runtime error: invalid memory address or nil pointer dereference
goroutine 20 [running]:
net/http.(*conn).serve.func1(0xc820147780)
	/usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x848a80, 0xc82000a230)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
html/template.(*Template).escape(0x0, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:79 +0x3c
html/template.(*Template).Execute(0x0, 0x7f8e35332458, 0xc82013e680, 0x83b960, 0xc820172e40, 0x0, 0x0)
	/usr/local/go/src/html/template/template.go:101 +0x34
gospatial/app.MapHandler(0x7f8e35332388, 0xc82013e680, 0xc8201568c0)
	/home/zack/Documents/gospatial2/src/gospatial/app/generalHandlers.go:21 +0x461
net/http.HandlerFunc.ServeHTTP(0x9a5e58, 0x7f8e35332388, 0xc82013e680, 0xc8201568c0)
	/usr/local/go/src/net/http/server.go:1618 +0x3a
github.com/gorilla/mux.(*Router).ServeHTTP(0xc820136000, 0x7f8e35332388, 0xc82013e680, 0xc8201568c0)
	/home/zack/Documents/gospatial2/src/github.com/gorilla/mux/mux.go:103 +0x270
net/http.serverHandler.ServeHTTP(0xc820147280, 0x7f8e35332388, 0xc82013e680, 0xc8201568c0)
	/usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820147780)
	/usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Comment by schollz** [comment]
It was the wrong route
